site_name: Kay Schneutzer | Leadership is about empathy
site_url:  https://schneutzi-81.github.io
site_description: 'Kay Schneutzer Vita'
site_author: 'Kay Schneutzer'
docs_dir: docs/

repo_name: 'https://github.com/schneutzi-81'
repo_url: 'https://github.com/schneutzi-81'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Kay Schneutzer

nav:
    - LinkedIn: https://www.linkedin.com/in/kay-schneutzer-50169817/
    - My Profile: https://github.com/schneutzi-81/schneutzi-81.github.io/raw/master/docs/assets/Profile%2BKay%2BSchneutzer.pdf
    - About me: index.md
    - Curriculum Vitae : https://github.com/schneutzi-81/schneutzi-81.github.io/raw/master/docs/assets/Kay%2BSchneutzer%2B-%2B%2BGlobal%2BBDM.pdf
  	- Professional Track of Record: TrackofRecord.md
    
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    primary: white
  
  features:
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Goangern
      name: Goangern on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kay-schneutzer-50169817/
      name: Kay Schneutzer on Linkedin
    - icon: fontawesome/brands/github
      link: https://github.com/schneutzi-81
      name: Schneutzi on github
  
markdown_extensions:
  - meta
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
  - print-site:
       add_to_navigation: true
       add_table_of_contents: false
       enumerate_headings: false
       add_print_site_banner: false
       path_to_pdf: "resume.pdf"
  
