site_name: Joe Doe
site_url:  https://holgerimbery.github.io/online-resume
site_description: 'online resume'
site_author: 'Holger Imbery'
docs_dir: docs/

repo_name: 'https://github.com/holgerimbery/online_resume/'
repo_url: 'https://github.com/holgerimbery/online_resume/'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2021 Holger Imbery

nav:
    - LinkedIn: https://www.linkedin.com/in/joedoe/
    - Resume: index.md
    
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    primary: white
  
  features:
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joedoe
      name: Joe Doe on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joedoe/
      name: Joe Doe on Linkedin
    - icon: fontawesome/brands/github
      link: https://github.com/joedoe
      name: Joe Doe on github
  
markdown_extensions:
  - meta
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
  - print-site:
       add_to_navigation: true
       add_table_of_contents: false
       enumerate_headings: false
       add_print_site_banner: false
       path_to_pdf: "resume.pdf"
  
