site_name: Kay Schneutzer
site_url: https://schneutzi-81.github.io
site_description: 'Kay Schneutzer — Leadership is about empathy'
site_author: 'Kay Schneutzer'
docs_dir: docs/

# Copyright
copyright: "&copy; 2024 Kay Schneutzer"

nav:
    - About: index.md
    - Track Record: trackofrecord.md
    - LinkedIn: https://www.linkedin.com/in/kay-schneutzer-50169817/
    - CV: https://github.com/schneutzi-81/schneutzi-81.github.io/raw/master/docs/assets/Kay%2BSchneutzer%2B-%2B%2BGlobal%2BBDM.pdf

theme:
  name: 'material'
  custom_dir: docs/overrides
  font: false
  palette:
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    logo: material/account-circle
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kay-schneutzer-50169817/
      name: Kay Schneutzer on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/schneutzi-81
      name: Schneutzi on GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Goangern
      name: Goangern on X

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - print-site:
       add_to_navigation: true
       add_table_of_contents: false
       enumerate_headings: false
       add_print_site_banner: false
       path_to_pdf: "resume.pdf"
